In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((4,5)) # its a 2D array since it has 2 sq. brackets

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,10) #10 evenly spaced points b/w 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(4) #Creation of identical matrix again a 2D

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5) # Random 1-D array for a uniform distribution 

array([0.74540285, 0.38982116, 0.69264202, 0.02076961, 0.03530144])

In [19]:
np.random.rand(5,4) # Random 1-D array for a uniform distribution

array([[0.50077673, 0.82654088, 0.65950461, 0.89061713],
       [0.81555669, 0.77644961, 0.9223802 , 0.08557033],
       [0.04946796, 0.04286155, 0.37646919, 0.65598475],
       [0.78086672, 0.62455775, 0.09728176, 0.36225741],
       [0.82665062, 0.28624662, 0.8001147 , 0.39650727]])

In [20]:
np.random.randn(2) # normal distribution

array([-0.21062706,  0.79411087])

In [21]:
np.random.randn(2,4) # for normal distribution / gaussian distribution

array([[-0.08432004, -0.06465866,  0.89269368, -0.4410232 ],
       [ 0.54763338,  0.20000534,  2.66583362,  0.67228949]])

In [22]:
np.random.randint(1,100) # Returns random integers from 'low'(inclusive) to 'high' (exclusive)

39

In [23]:
np.random.randint(1,100,10) # for 10 random integers

array([15, 40, 72, 51, 60, 11, 55, 71, 75, 66])

In [24]:
arr = np.arange(25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(0, 50, 10)

In [27]:
ranarr

array([43, 30, 48, 12,  6, 36, 26, 12, 42, 25])

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
arr.reshape(5,50) # Number of digits must be exactly sufficient to call upon reshape

ValueError: cannot reshape array of size 25 into shape (5,50)

In [30]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [31]:
ranarr

array([43, 30, 48, 12,  6, 36, 26, 12, 42, 25])

In [32]:
ranarr.max()

48

In [33]:
ranarr.min()

6

In [34]:
ranarr.argmax()

2

In [35]:
ranarr.argmin()

4

In [37]:
arr.shape      #Notice the comma(,) which indicates its 1D

(25,)

In [38]:
arr = arr.reshape(5,5)

In [39]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
arr.shape

(5, 5)

In [42]:
arr.dtype

dtype('int32')

In [43]:
from numpy.random import randint

In [44]:
randint(2,10)

9